### ISSUE TITLE
We may need to move the project to a create-react-app one 

### ISSUE THREAD

**Issue by adoankim** [ArtifactGames/abandoned-prealpha-copyplash-web-client#3]
Having all the components on the `main.js` may not be the best solution. We didn't finished yet the main screen an it has `169` lines now 😅 .

If we move the project to a [create-react-app](https://github.com/facebook/create-react-app) base we will be able to escalate and maintain it more easier.

**Comment by zlotny** [comment]
It's now a create-react-app based project, at the unstable branch.
